import type { Metadata } from "next";
import StyledComponentsRegistry from './registry';
import GlobalStyles from "./styles/GlobalStyles";
import AuthProvider from "./components/AuthProvider";
import { Navbar, SideNav } from "./components";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <StyledComponentsRegistry>
          <GlobalStyles />
          <AuthProvider>
            <Navbar />
            <div style={{ display: 'flex', minHeight: '100vh' }}>
              <SideNav />
              <main className="flex-grow">{children}</main>
            </div>
          </AuthProvider>
        </StyledComponentsRegistry>
      </body>
    </html>
  );
}
